/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}', // Make sure this line is included
  ],
  theme: {
    extend: {
      // --- Add this typography section ---
      typography: (theme) => ({
        invert: { // Apply styles when using 'prose-invert' (for dark mode)
          css: {
            '--tw-prose-body': theme('colors.gray[300]'),
            '--tw-prose-headings': theme('colors.white'),
            '--tw-prose-lead': theme('colors.gray[400]'),
            '--tw-prose-links': theme('colors.blue[400]'),
            '--tw-prose-bold': theme('colors.white'),
            '--tw-prose-counters': theme('colors.gray[400]'),
            '--tw-prose-bullets': theme('colors.gray[600]'),
            '--tw-prose-hr': theme('colors.gray[700]'),
            '--tw-prose-quotes': theme('colors.gray[100]'),
            '--tw-prose-quote-borders': theme('colors.gray[700]'),
            '--tw-prose-captions': theme('colors.gray[400]'),
            '--tw-prose-code': theme('colors.white'),
            '--tw-prose-pre-code': theme('colors.gray[300]'),
            '--tw-prose-pre-bg': theme('colors.gray[800]'), // Code block background
            '--tw-prose-th-borders': theme('colors.gray[600]'),
            '--tw-prose-td-borders': theme('colors.gray[700]'),

            // --- Customizations ---
            h1: {
              fontWeight: '700',
              marginTop: theme('spacing.8'), // Add more space above h1
              marginBottom: theme('spacing.4'),
            },
            h2: {
              fontWeight: '600',
              marginTop: theme('spacing.6'), // Add more space above h2
              marginBottom: theme('spacing.3'),
            },
            h3: {
              fontWeight: '600',
              marginTop: theme('spacing.5'),
              marginBottom: theme('spacing.2'),
            },
            p: {
              marginTop: theme('spacing.2'), // Add a bit more space between paragraphs
              marginBottom: theme('spacing.2'),
            },
            ul: {
              marginTop: theme('spacing.2'),
              marginBottom: theme('spacing.2'),
              paddingLeft: theme('spacing.5'), // Indent lists a bit more
            },
            ol: {
              marginTop: theme('spacing.2'),
              marginBottom: theme('spacing.2'),
              paddingLeft: theme('spacing.5'),
            },
            li: {
              marginTop: theme('spacing.1'), // Space between list items
              marginBottom: theme('spacing.1'),
            },
            a: {
              color: theme('colors.blue[400]'), // Make links blue
              textDecoration: 'none', // Remove underline by default
              '&:hover': {
                color: theme('colors.blue[300]'), // Lighter blue on hover
                textDecoration: 'underline', // Add underline on hover
              },
            },
             code: { // Inline code style
              backgroundColor: theme('colors.gray[700]'),
              padding: '0.2em 0.4em',
              margin: '0 0.1em', // Add slight margin around inline code
              borderRadius: theme('borderRadius.sm'),
              fontWeight: '500',
              fontSize: '0.9em', // Slightly smaller font for inline code
            },
            'code::before': { content: 'none' }, // Remove default backticks for inline code
            'code::after': { content: 'none' },
            pre: { // Code block style
               marginTop: theme('spacing.4'),
               marginBottom: theme('spacing.4'),
               padding: theme('spacing.4'), // Add padding to code blocks
               borderRadius: theme('borderRadius.md'), // Round corners
            }
          },
        },
      }),
      // --- End typography section ---

      // Keep this if it was generated by default
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  // Add the typography plugin
  plugins: [
    require('@tailwindcss/typography'),
  ],
};